# Generated by Django 4.1.2 on 2022-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-status', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'get_latest_by': ['created_on'], 'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='wordcount',
            field=models.IntegerField(default=0),
        ),
    ]
